[package]
name = "fusion-tendermint-proxy"
authors.workspace = true
edition.workspace = true
version.workspace = true
repository.workspace = true
homepage.workspace = true
license.workspace = true

[dependencies]
anyhow                           = { workspace = true }
chrono                           = { workspace = true, default-features = false, features = ["serde"] }
futures                          = { workspace = true }
hex                              = { workspace = true }
http                             = { workspace = true }
metrics                          = { workspace = true }
pbjson-types                     = { workspace = true }
fusion-proto                   = { workspace = true, features = ["rpc", "tendermint"] }
fusion-transaction             = { workspace = true }
pin-project                      = { workspace = true }
pin-project-lite                 = { workspace = true }
sha2                             = { workspace = true }
tap                              = { workspace = true }
tendermint                       = { workspace = true }
tendermint-config                = { workspace = true }
tendermint-light-client-verifier = { workspace = true }
tendermint-proto                 = { workspace = true }
tendermint-rpc                   = { workspace = true, features = ["http-client"] }
tokio                            = { workspace = true, features = ["full"] }
tokio-stream                     = { workspace = true }
tokio-util                       = { workspace = true }
tonic                            = { workspace = true }
tower                            = { workspace = true, features = ["full"] }
tower-service                    = { workspace = true }
tracing                          = { workspace = true }
url                              = { workspace = true }
