[package]
name = "decaf377-ka"
authors.workspace = true
edition.workspace = true
version.workspace = true
repository.workspace = true
homepage.workspace = true
license.workspace = true

[features]
default = ["std"]
std = ["ark-ff/std"]

[dependencies]
ark-ff = {workspace = true, default-features = false}
decaf377 = {workspace = true}
hex = {workspace = true}
rand_core = {workspace = true, features = ["getrandom"]}
thiserror = {workspace = true}
zeroize = "1.4"
zeroize_derive = "1.3"

[dev-dependencies]
proptest = {workspace = true}
